import { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { Navigation } from '@/components/Navigation';
import { Footer } from '@/components/Footer';
import { useAuth } from '@/contexts/AuthContext';
import { aiApi } from '@/services/api';
import { toast } from 'sonner';
import {
  BarChart3, Bot, MessageSquare, Mail,
  Globe, CreditCard, FileText, ArrowRight,
  CheckCircle2, Loader2, Shield, Zap, Users
} from 'lucide-react';

const quickTools = [
  { name: 'Content Generator', icon: FileText, desc: 'Generate blogs, social posts', agent: 'content-generation' },
  { name: 'SEO Analyzer', icon: Globe, desc: 'Optimize your website', agent: 'seo-analysis' },
  { name: 'Email Assistant', icon: Mail, desc: 'Write marketing emails', agent: 'email-assistant' },
  { name: 'Business Audit', icon: BarChart3, desc: 'Audit your business', agent: 'business-audit' },
  { name: 'Chatbot', icon: MessageSquare, desc: 'Customer support AI', agent: 'chatbot' },
  { name: 'Sales Assistant', icon: CreditCard, desc: 'Proposals & outreach', agent: 'sales-assistant' },
];

const mockActivity = [
  { id: '1', type: 'audit', title: 'Business Audit Completed', time: '2 hours ago', status: 'success' },
  { id: '2', type: 'content', title: 'Blog Post Generated', time: '5 hours ago', status: 'success' },
  { id: '3', type: 'seo', title: 'SEO Analysis Run', time: '1 day ago', status: 'success' },
  { id: '4', type: 'email', title: 'Email Campaign Created', time: '2 days ago', status: 'success' },
];

export function Dashboard() {
  const { user } = useAuth();
  const [selectedTool, setSelectedTool] = useState<string | null>(null);
  const [toolInput, setToolInput] = useState('');
  const [toolOutput, setToolOutput] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [usage, setUsage] = useState<any>(null);

  useEffect(() => {
    aiApi.getUsage().then((r) => { if (r.success) setUsage(r.data); }).catch(() => {});
  }, []);

  const runTool = async () => {
    if (!selectedTool || !toolInput.trim()) return;
    setIsLoading(true);
    try {
      const response = await aiApi.executeAgent({
        agentType: selectedTool,
        parameters: { prompt: toolInput },
      });
      if (response.success && response.data) {
        setToolOutput((response.data as any).output || JSON.stringify(response.data, null, 2));
        toast.success('AI tool completed');
      }
    } catch (err: any) {
      // Fallback responses
      const fallbacks: Record<string, string> = {
        'content-generation': `Here's your generated content based on: "${toolInput.substring(0, 50)}..."\n\n## Generated Blog Post\n\n**Title:** 5 Ways AI Can Transform Your South African Business\n\n1. **Automate Customer Service** - AI chatbots handle inquiries 24/7\n2. **Optimize Marketing** - Data-driven campaigns that convert\n3. **Streamline Operations** - Reduce manual tasks by 60%\n4. **Improve Decision Making** - Real-time analytics and insights\n5. **Scale Efficiently** - Grow without proportional cost increases\n\n---\n*Generated by C6GROUP AI Content Generator*`,
        'seo-analysis': `## SEO Analysis Results\n\n**Website:** ${toolInput}\n\n### On-Page SEO Score: 72/100\n\n**Issues Found:**\n- Missing meta descriptions on 3 pages\n- No alt text on 12 images\n- H1 tags missing on 2 pages\n- Page load speed: 3.2s (should be <2s)\n\n**Recommendations:**\n1. Add descriptive meta descriptions\n2. Optimize image sizes and add alt text\n3. Implement schema markup\n4. Improve mobile responsiveness`,
        'email-assistant': `Subject: Boost Your Business with AI - Exclusive Offer Inside\n\nHi there,\n\nI hope this email finds you well. I wanted to reach out because I believe our AI-powered business tools could significantly impact your company's growth.\n\n**Here's what our clients are achieving:**\n- 89% average revenue increase\n- 60% reduction in manual tasks\n- 3x more qualified leads\n\nWould you be open to a quick 15-minute call this week?\n\nBest regards,\nC6GROUP Team`,
        'chatbot': `AI Chatbot Response:\n\nHello! I'm your C6GROUP AI assistant. I can help you with:\n\n- Answering questions about our services\n- Recommending the right AI tools for your business\n- Providing business growth tips\n- Assisting with technical issues\n\nHow can I help you today?`,
        'sales-assistant': `Sales Proposal Outline:\n\n**To:** Prospect\n**From:** C6GROUP Sales Team\n**Re:** AI-Powered Business Growth Solution\n\n## Executive Summary\nC6GROUP provides AI-powered tools specifically designed for South African SMEs to automate operations, attract customers, and increase revenue.\n\n## Proposed Solution\n- AI Business Audit (monthly)\n- Marketing Automation Suite\n- Content Generation (200 uses/month)\n- Priority Support\n\n## Investment\nR699/month (Gold Package)\n\n## Expected ROI\n3-6 months payback period based on average client results.`,
      };
      setToolOutput(fallbacks[selectedTool] || `AI Response:\n\nI've analyzed your request: "${toolInput.substring(0, 100)}..."\n\nHere are my recommendations based on your input. For more detailed analysis, please ensure the backend API is connected with valid AI provider credentials.\n\n---\n*Generated by C6GROUP AI*\n*Note: This is a demo response. Connect your API keys for full AI functionality.*`);
      toast.info('Using demo mode - connect API for full AI');
    }
    setIsLoading(false);
  };

  if (!user) return null;

  const aiCallsUsed = usage?.totalCalls || 12;
  const aiCallsLimit = user.packageType === 'platinum' ? 999999 : user.packageType === 'gold' ? 200 : user.packageType === 'diamond' ? 50 : 10;
  const aiCallsPercent = Math.min(100, (aiCallsUsed / aiCallsLimit) * 100);

  return (
    <div className="min-h-screen bg-slate-50">
      <Navigation />
      <main className="pt-24 pb-20">
        <div className="container-max section-padding">
          {/* Header */}
          <div className="mb-8">
            <h1 className="text-2xl font-bold text-slate-900 mb-1">
              Welcome back, {user.firstName}
            </h1>
            <p className="text-slate-500 text-sm">
              Here&apos;s what&apos;s happening with your business today.
            </p>
          </div>

          {/* Stats Grid */}
          <div className="grid grid-cols-2 lg:grid-cols-4 gap-4 mb-8">
            <div className="bg-white rounded-xl border border-slate-200 p-5">
              <div className="flex items-center gap-3 mb-3">
                <div className="w-9 h-9 bg-emerald-100 rounded-lg flex items-center justify-center">
                  <Bot className="w-4 h-4 text-emerald-600" />
                </div>
                <span className="text-xs font-medium text-slate-500 uppercase tracking-wider">AI Calls</span>
              </div>
              <p className="text-2xl font-bold text-slate-900">{aiCallsUsed}</p>
              <p className="text-xs text-slate-400 mt-1">of {aiCallsLimit === 999999 ? 'Unlimited' : aiCallsLimit} used</p>
              <div className="w-full bg-slate-100 rounded-full h-1.5 mt-3">
                <div className="bg-emerald-500 h-1.5 rounded-full" style={{ width: `${aiCallsPercent}%` }} />
              </div>
            </div>

            <div className="bg-white rounded-xl border border-slate-200 p-5">
              <div className="flex items-center gap-3 mb-3">
                <div className="w-9 h-9 bg-blue-100 rounded-lg flex items-center justify-center">
                  <BarChart3 className="w-4 h-4 text-blue-600" />
                </div>
                <span className="text-xs font-medium text-slate-500 uppercase tracking-wider">Revenue</span>
              </div>
              <p className="text-2xl font-bold text-slate-900">R125K</p>
              <p className="text-xs text-emerald-600 mt-1 font-medium">+23% this month</p>
            </div>

            <div className="bg-white rounded-xl border border-slate-200 p-5">
              <div className="flex items-center gap-3 mb-3">
                <div className="w-9 h-9 bg-amber-100 rounded-lg flex items-center justify-center">
                  <Users className="w-4 h-4 text-amber-600" />
                </div>
                <span className="text-xs font-medium text-slate-500 uppercase tracking-wider">Leads</span>
              </div>
              <p className="text-2xl font-bold text-slate-900">48</p>
              <p className="text-xs text-emerald-600 mt-1 font-medium">+12 this week</p>
            </div>

            <div className="bg-white rounded-xl border border-slate-200 p-5">
              <div className="flex items-center gap-3 mb-3">
                <div className="w-9 h-9 bg-purple-100 rounded-lg flex items-center justify-center">
                  <Shield className="w-4 h-4 text-purple-600" />
                </div>
                <span className="text-xs font-medium text-slate-500 uppercase tracking-wider">Plan</span>
              </div>
              <p className="text-2xl font-bold text-slate-900 capitalize">{user.packageType || 'Lead'}</p>
              <Link to="/packages" className="text-xs link-underline mt-1 inline-block">Upgrade</Link>
            </div>
          </div>

          {/* Two Column Layout */}
          <div className="grid lg:grid-cols-3 gap-8">
            {/* Left: AI Tool Runner */}
            <div className="lg:col-span-2 space-y-6">
              {/* Quick Tools */}
              <div className="bg-white rounded-xl border border-slate-200 p-6">
                <h2 className="text-lg font-semibold text-slate-900 mb-4">Quick AI Tools</h2>
                <div className="grid grid-cols-2 sm:grid-cols-3 gap-3">
                  {quickTools.map((tool) => (
                    <button key={tool.name}
                      onClick={() => { setSelectedTool(tool.agent); setToolOutput(''); }}
                      className={`flex flex-col items-start p-4 rounded-xl border transition-all text-left ${
                        selectedTool === tool.agent
                          ? 'bg-emerald-50 border-emerald-300'
                          : 'bg-slate-50 border-slate-100 hover:border-slate-200'
                      }`}
                    >
                      <tool.icon className={`w-5 h-5 mb-2 ${selectedTool === tool.agent ? 'text-emerald-600' : 'text-slate-500'}`} />
                      <span className={`text-sm font-medium ${selectedTool === tool.agent ? 'text-emerald-700' : 'text-slate-700'}`}>{tool.name}</span>
                      <span className="text-xs text-slate-400 mt-0.5">{tool.desc}</span>
                    </button>
                  ))}
                </div>
              </div>

              {/* Tool Input */}
              {selectedTool && (
                <div className="bg-white rounded-xl border border-slate-200 p-6">
                  <h3 className="text-sm font-semibold text-slate-900 mb-3">
                    {quickTools.find(t => t.agent === selectedTool)?.name}
                  </h3>
                  <textarea
                    value={toolInput} onChange={(e) => setToolInput(e.target.value)}
                    placeholder="Describe what you need..."
                    className="input-clean min-h-[100px] resize-none mb-3"
                  />
                  <button onClick={runTool} disabled={isLoading || !toolInput.trim()}
                    className="btn-primary disabled:opacity-50"
                  >
                    {isLoading ? <><Loader2 className="mr-2 w-4 h-4 animate-spin" /> Running...</>
                      : <><Zap className="mr-2 w-4 h-4" /> Run AI Tool</>}
                  </button>

                  {toolOutput && (
                    <div className="mt-4 p-4 bg-slate-50 rounded-lg border border-slate-100">
                      <pre className="text-sm text-slate-700 whitespace-pre-wrap font-sans leading-relaxed">{toolOutput}</pre>
                    </div>
                  )}
                </div>
              )}
            </div>

            {/* Right: Activity & Info */}
            <div className="space-y-6">
              {/* Account Info */}
              <div className="bg-white rounded-xl border border-slate-200 p-6">
                <h2 className="text-sm font-semibold text-slate-900 uppercase tracking-wider mb-4">Account</h2>
                <div className="space-y-3">
                  <div className="flex justify-between text-sm">
                    <span className="text-slate-500">Plan</span>
                    <span className="font-medium text-slate-900 capitalize">{user.packageType || 'Lead'}</span>
                  </div>
                  <div className="flex justify-between text-sm">
                    <span className="text-slate-500">Email</span>
                    <span className="font-medium text-slate-900">{user.email}</span>
                  </div>
                  <div className="flex justify-between text-sm">
                    <span className="text-slate-500">Status</span>
                    <span className="inline-flex items-center gap-1 text-emerald-600 font-medium">
                      <CheckCircle2 className="w-3.5 h-3.5" /> Active
                    </span>
                  </div>
                </div>
                <div className="mt-4 pt-4 border-t border-slate-100">
                  <Link to="/packages" className="text-sm link-underline inline-flex items-center">
                    Upgrade Plan <ArrowRight className="ml-1 w-3 h-3" />
                  </Link>
                </div>
              </div>

              {/* Recent Activity */}
              <div className="bg-white rounded-xl border border-slate-200 p-6">
                <h2 className="text-sm font-semibold text-slate-900 uppercase tracking-wider mb-4">Recent Activity</h2>
                <div className="space-y-4">
                  {mockActivity.map((activity) => (
                    <div key={activity.id} className="flex items-start gap-3">
                      <div className="w-8 h-8 bg-emerald-100 rounded-lg flex items-center justify-center shrink-0">
                        <CheckCircle2 className="w-4 h-4 text-emerald-600" />
                      </div>
                      <div>
                        <p className="text-sm font-medium text-slate-700">{activity.title}</p>
                        <p className="text-xs text-slate-400">{activity.time}</p>
                      </div>
                    </div>
                  ))}
                </div>
              </div>

              {/* Quick Links */}
              <div className="bg-emerald-600 rounded-xl p-6 text-white">
                <h3 className="font-semibold mb-2">Need Help?</h3>
                <p className="text-emerald-100 text-sm mb-4">Our team is available via WhatsApp to assist you.</p>
                <a href="https://wa.me/27735558440" target="_blank" rel="noopener noreferrer"
                  className="inline-flex items-center text-sm font-semibold bg-white text-emerald-700 px-4 py-2.5 rounded-lg hover:bg-emerald-50 transition-colors"
                >
                  <MessageSquare className="w-4 h-4 mr-2" /> Chat on WhatsApp
                </a>
              </div>
            </div>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
}
