const packages = [
  {
    id: 'start',
    name: 'Start',
    price: 0,
    tagline: 'Get Found',
    description: 'Start with the intelligence and visibility foundations your business needs.',
    icon: Zap,
    popular: false,
    features: ['Free AI Business Audit','Basic directory listing','10 AI tool uses/mo','Basic insights','WhatsApp support'],
  },
  {
    id: 'diamond',
    name: 'Diamond',
    price: 4995,
    tagline: 'AI Receptionist for Rentals',
    description: 'Rental enquiries, WhatsApp auto-replies, listing optimizer.',
    icon: TrendingUp,
    popular: true,
    features: ['Everything in Start','AI receptionist for rentals','500 WhatsApp auto-replies','Listing optimizer','Reputation support','Growth reporting'],
  },
  {
    id: 'gold',
    name: 'Gold',
    price: 9995,
    tagline: 'Sales + Rentals Machine',
    description: 'Qualify leads, book viewings, automate follow-ups.',
    icon: Rocket,
    popular: false,
    features: ['Everything in Diamond','Sales lead qualification','Viewing booking','2000 WhatsApp/mo','Email automation','Advanced analytics'],
  },
  {
    id: 'platinum',
    name: 'Platinum',
    price: 24995,
    tagline: 'Full AI Staff Member',
    description: '1 Full AI Staff + 10k messages + Property24 integration.',
    icon: Building2,
    popular: false,
    features: ['Everything in Gold','1 Full AI Staff Member','10000 WhatsApp/mo','Property24 integration','Custom workflows','Dedicated support'],
  },
];